from __future__ import annotations

import json
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
CASES_PATH = ROOT / "e2e" / "cases.json"


def case(
    number: int,
    case_id: str,
    requirement: str,
    small_test: str,
    larger_test: str,
    message: str,
    *,
    tools: list[str],
    expected: str,
    pass_criteria: str,
    failures: list[str],
    tags: list[str] | None = None,
    setup: list[str] | None = None,
    size: str = "small",
    timeout: int = 240,
    assertions: dict[str, Any] | None = None,
    depends_on: list[str] | None = None,
    pause_after_seconds: float | None = None,
    post_wait_schedule_seconds: int | None = None,
    input_kind: str | None = None,
) -> dict[str, Any]:
    payload: dict[str, Any] = {
        "number": number,
        "id": case_id,
        "requirement": requirement,
        "small_test": small_test,
        "larger_test": larger_test,
        "message": message,
        "setup": setup or [],
        "tags": tags or [],
        "tools_required": tools,
        "expected_behavior": expected,
        "pass_criteria": pass_criteria,
        "failure_cases": failures,
        "size": size,
        "timeout_seconds": timeout,
        "assertions": {"final_status_in": ["completed"], **(assertions or {})},
    }
    if depends_on:
        payload["depends_on"] = depends_on
    if pause_after_seconds is not None:
        payload["pause_after_seconds"] = pause_after_seconds
    if post_wait_schedule_seconds is not None:
        payload["post_wait_schedule_seconds"] = post_wait_schedule_seconds
    if input_kind is not None:
        payload["input_kind"] = input_kind
    return payload


CASES = [
    case(
        1,
        "desktop_inspection",
        "Inspect the actual desktop and summarize visible items.",
        "Tell me what is on my desktop right now.",
        "Look at my desktop, identify the visible files, folders, apps, and open windows, and summarize what you see.",
        "Tell me what is on my desktop right now.",
        tools=["computer.use:observe"],
        expected="The agent observes the real desktop state and reports visible windows, apps, and desktop items when available.",
        pass_criteria="The response is grounded in the desktop observation and does not invent unrelated items.",
        failures=["No desktop observation tool ran.", "The reply guesses without screenshot or UI evidence.", "The summary lists unrelated items."],
        tags=["desktop", "safe"],
        assertions={
            "tools_all": ["computer.use:observe"],
            "metadata_any": ["desktop_observation", "screenshot_path", "screenshot_uri"],
            "bot_reply_contains_any": ["desktop", "screen", "window", "screenshot"],
        },
    ),
    case(
        2,
        "folder_open_inspection",
        "Open or inspect a requested folder and summarize its contents.",
        "Open the folder named Downloads and tell me what files are inside.",
        "Open the folder on my desktop that looks most relevant to invoices, inspect what is inside, and tell me what kind of files it contains.",
        "Inspect the folder {{documents_folder}} and tell me what files and subfolders are inside.",
        tools=["filesystem.manage:inspect_folder"],
        expected="The agent uses filesystem inspection when a concrete folder path is known, and asks for clarification only when the folder cannot be identified safely.",
        pass_criteria="The reported files and subfolders match the target folder.",
        failures=["Wrong folder inspected.", "The agent uses a stale artifact instead of the folder.", "The reply omits the actual contents."],
        setup=["documents_fixture"],
        tags=["filesystem"],
        assertions={
            "tools_all": ["filesystem.manage:inspect_folder"],
            "metadata_any": ["file_manifest", "entries", "summary"],
            "bot_reply_contains_any": ["files", "folder", "notes", "budget", "sample"],
        },
    ),
    case(
        3,
        "pdf_open_summary",
        "Find/open a PDF and summarize based on content.",
        "Open this PDF and tell me what it is about.",
        "Open one of the folders on my desktop, find a PDF inside it, open it, and explain what the PDF is about.",
        "Open the desktop folder {{desktop_folder}}, find the PDF inside it, and tell me what the PDF is about.",
        tools=["document.manage:summarize_pdf"],
        expected="The agent locates the PDF and summarizes its extracted content, not just the filename.",
        pass_criteria="The summary mentions content from the fixture PDF about automation, browser testing, or artifact delivery.",
        failures=["Summary is based only on filename.", "Wrong file opened.", "PDF content extraction error is hidden."],
        setup=["desktop_pdf_fixture"],
        tags=["documents"],
        assertions={
            "tools_all": ["document.manage:summarize_pdf"],
            "metadata_any": ["document_summary", "document_path", "summary"],
            "artifacts_min": 1,
            "bot_reply_contains_any": ["PDF", "automation", "browser", "artifact"],
        },
    ),
    case(
        4,
        "send_found_pdf",
        "Send a found/opened PDF file back to the user.",
        "Send me that PDF file.",
        "Find the PDF we just discussed, attach it or export it, and send it back to me.",
        "Send me the PDF file at {{pdf_path}}.",
        tools=["artifact.deliver:send_file"],
        expected="The agent resolves the requested PDF and sends the actual file through Telegram.",
        pass_criteria="Telegram receives the correct PDF file or a clear unavailable-file explanation.",
        failures=["Recent artifact cache is used instead of the requested path.", "No Telegram media is sent.", "Wrong file is delivered."],
        setup=["desktop_pdf_fixture"],
        tags=["documents", "telegram_delivery"],
        assertions={
            "tools_all": ["artifact.deliver:send_file"],
            "artifacts_min": 1,
            "telegram_media_min": 1,
            "bot_reply_contains_any": ["PDF", "file", "sent"],
        },
    ),
    case(
        5,
        "screenshot_capture",
        "Capture and send a current desktop screenshot.",
        "Send me a screenshot of the desktop.",
        "Open the browser, go to this website, then send me a screenshot of the browser and the desktop state.",
        "Send me a screenshot of the desktop.",
        tools=["computer.use:observe", "artifact.deliver:send_screenshot"],
        expected="The agent captures the current desktop state and sends that screenshot to Telegram.",
        pass_criteria="The screenshot is current, delivered as Telegram media, and tied to this task.",
        failures=["Screenshot is stale.", "Task stops for a separate approval despite admin full access.", "No media reaches Telegram."],
        tags=["desktop", "telegram_delivery", "safe"],
        assertions={
            "tools_all": ["computer.use:observe", "artifact.deliver:send_screenshot"],
            "metadata_any": ["screenshot_path", "screenshot_uri"],
            "telegram_media_min": 1,
        },
    ),
    case(
        6,
        "organize_by_filename",
        "Organize files in a folder based on filenames.",
        "Organize this folder based on the file names.",
        "Look at all files in this folder. Based on their file names, create sensible category folders and move the files into them.",
        "Look at all files in {{documents_folder}}. Based on their file names, create sensible category folders and move the files into them, then tell me what changed.",
        tools=["filesystem.manage:organize_plan", "filesystem.manage:apply_manifest"],
        expected="The agent proposes and applies a safe move manifest inside the configured folder root.",
        pass_criteria="Files are moved logically, no file is lost, and changed paths are reported.",
        failures=["Files move outside the allowed root.", "No manifest is recorded.", "Moved paths do not exist."],
        setup=["documents_fixture"],
        tags=["filesystem"],
        assertions={
            "tools_all": ["filesystem.manage:organize_plan", "filesystem.manage:apply_manifest"],
            "metadata_any": ["manifest", "changed_paths", "organized_paths"],
            "changed_paths_min": 1,
            "bot_reply_contains_any": ["moved", "changed", "organized"],
        },
    ),
    case(
        7,
        "organize_by_content",
        "Organize documents by inspecting file contents.",
        "Look at these documents and organize them by topic.",
        "Inspect the documents in this folder, understand what each file is about, create new folders based on their topics, and move each document into the right folder.",
        "Inspect the documents in {{documents_folder}}, organize them by topic based on their contents, and tell me what changed.",
        tools=["filesystem.manage:inspect_folder", "filesystem.manage:organize_plan", "filesystem.manage:apply_manifest"],
        expected="The agent reads supported document contents, creates topic folders, moves files, and flags ambiguous files.",
        pass_criteria="The organization reflects actual contents, not only extensions or filenames.",
        failures=["Categorization ignores content.", "Ambiguous files are randomly moved.", "Destructive action is taken without evidence."],
        setup=["documents_fixture"],
        tags=["filesystem"],
        size="medium",
        assertions={
            "tools_all": ["filesystem.manage:organize_plan", "filesystem.manage:apply_manifest"],
            "metadata_any": ["manifest", "changed_paths", "content_categories"],
            "changed_paths_min": 1,
        },
    ),
    case(
        8,
        "organize_images_by_visual_content",
        "Organize images based on what is shown in them.",
        "Organize these images based on what is shown in them.",
        "Look through this image folder, identify what each image appears to contain, create category folders such as screenshots, people, documents, receipts, products, or other useful categories, and move the images accordingly.",
        "Look through {{image_folder}}, identify what each image appears to contain, create useful category folders, move the images accordingly, and tell me what changed.",
        tools=["filesystem.manage:inspect_folder", "computer.use:observe or vision adapter", "filesystem.manage:apply_manifest"],
        expected="The agent visually inspects images when a vision provider is available and organizes them by visual content.",
        pass_criteria="Images are categorized by visual content; unsupported vision fails clearly instead of guessing.",
        failures=["Images are categorized only by extension.", "The agent invents visual content.", "Vision unavailable is not reported."],
        setup=["image_fixture"],
        tags=["filesystem", "vision", "long"],
        size="medium",
        timeout=420,
        assertions={
            "tools_any": ["filesystem.manage:organize_plan", "computer.use:run_goal"],
            "metadata_any": ["visual_categories", "changed_paths", "unsupported_capability"],
        },
    ),
    case(
        10,
        "rename_files_by_content",
        "Rename files based on their contents.",
        "Rename these files based on their contents.",
        "Inspect every file in this folder, create clearer filenames based on what each file is about, rename them consistently, and give me a before-and-after table.",
        "Inspect every file in {{documents_folder}}, create clearer filenames based on what each file is about, rename them consistently, and give me a before-and-after table.",
        tools=["filesystem.manage:inspect_folder", "filesystem.manage:organize_plan", "filesystem.manage:apply_manifest"],
        expected="The agent prepares safe renames, avoids overwrites, preserves extensions, and reports before/after names.",
        pass_criteria="Renamed files are understandable, unique, traceable, and remain inside the folder.",
        failures=["Extension is lost.", "Overwrite risk is ignored.", "Before/after mapping is missing."],
        setup=["documents_fixture"],
        tags=["filesystem"],
        size="medium",
        assertions={
            "tools_any": ["filesystem.manage:apply_manifest"],
            "metadata_any": ["rename_manifest", "changed_paths"],
            "bot_reply_contains_any": ["before", "after", "renamed"],
        },
    ),
    case(
        11,
        "safe_file_operations",
        "Avoid destructive changes without explicit approval.",
        "Clean up this folder.",
        "Organize this folder, remove duplicates if any, and delete unnecessary files.",
        "Clean up {{documents_folder}}, organize what is safe to move, but do not delete or overwrite anything unless I explicitly approve it.",
        tools=["filesystem.manage:organize_plan", "filesystem.manage:apply_manifest"],
        expected="The agent may move/copy/rename when clear, but blocks delete/overwrite until explicit approval.",
        pass_criteria="No delete or overwrite occurs without explicit approval; blocked actions are explained.",
        failures=["Deletes files without approval.", "Overwrites existing files.", "Does not distinguish reversible from destructive operations."],
        setup=["documents_fixture"],
        tags=["filesystem", "safety"],
        assertions={
            "tools_all": ["filesystem.manage:organize_plan"],
            "metadata_any": ["manifest", "blocked_actions", "changed_paths"],
            "bot_reply_contains_any": ["delete", "approval", "moved", "safe"],
        },
    ),
    case(
        12,
        "progress_reporting",
        "Send real progress updates for long tasks.",
        "Organize this folder and give me a progress update every one minute.",
        "Organize a folder with many files. If the task takes more than one or two minutes, send interim updates showing what has been scanned, what is being processed, approximate progress, and what remains.",
        "Organize {{documents_folder}} by file names and give me a progress update every one minute while you work.",
        tools=["filesystem.manage:organize_plan", "filesystem.manage:apply_manifest", "progress notifier"],
        expected="For a long-running task, progress updates describe actual scanned, processed, moved, blocked, or remaining work.",
        pass_criteria="Progress updates are based on real task state and respect the requested cadence when practical.",
        failures=["Generic fake progress is sent.", "No updates arrive for a long task.", "Cadence is ignored."],
        setup=["documents_fixture"],
        tags=["filesystem", "long"],
        size="long-running",
        timeout=600,
        assertions={
            "tools_all": ["filesystem.manage:organize_plan"],
            "progress_updates_min": 1,
            "metadata_any": ["progress", "changed_paths", "manifest"],
        },
    ),
    case(
        13,
        "browser_open_navigation",
        "Open a browser, navigate to a website, verify, and screenshot.",
        "Open the browser and go to example.com.",
        "Open the browser, go to this website, wait for the page to load, tell me what page opened, and send me a screenshot.",
        "Open the browser, go to {{fixture_base_url}}/index.html, wait for it to load, tell me what page opened, and send me a screenshot.",
        tools=["browser.open:screenshot", "artifact.deliver:send_screenshot"],
        expected="The browser reaches the target page, verifies title/url, captures screenshot, and sends it.",
        pass_criteria="The screenshot and reported URL/title match the fixture page.",
        failures=["Wrong tab captured.", "Page did not load.", "No screenshot delivered."],
        setup=["local_web_fixture"],
        tags=["browser", "telegram_delivery", "safe"],
        assertions={
            "tools_all": ["browser.open:screenshot", "artifact.deliver:send_screenshot"],
            "metadata_any": ["browser_url", "page_title", "screenshot_path"],
            "urls_min": 1,
            "telegram_media_min": 1,
        },
    ),
    case(
        14,
        "web_search_first_result",
        "Search the web, open a first result, and summarize it.",
        "Search this phrase and tell me the top results.",
        "Open the browser, search for this topic, open the first result, read the page, and tell me what it is about.",
        "Open the browser, search for Python official documentation, open the first result, read the page, and tell me what it is about.",
        tools=["browser.open:research"],
        expected="The agent searches, opens a result, reads the opened page, and summarizes with page title/source.",
        pass_criteria="The summary is based on the opened page and includes source evidence.",
        failures=["Only search snippets are summarized.", "No result page is opened.", "The result source is missing."],
        tags=["browser", "internet"],
        size="medium",
        timeout=420,
        assertions={
            "tools_any": ["browser.open:research", "browser.open:research_pages"],
            "metadata_any": ["browser_url", "page_title", "browser_state"],
            "urls_min": 1,
            "bot_reply_contains_any": ["page", "summary", "source", "documentation"],
        },
    ),
    case(
        15,
        "deep_web_search_50_pages",
        "Search many pages and summarize grouped findings.",
        "Search the web and give me the best results.",
        "Search at least 50 pages about this topic, group the findings, identify the most useful sources, and summarize the results.",
        "Search at least 50 pages about local LLM deployment on Windows, group the findings, identify useful sources, and summarize the results.",
        tools=["browser.open:research_pages"],
        expected="The agent tracks visited pages, deduplicates sources, groups findings, and does not claim pages it did not inspect.",
        pass_criteria="The report includes visited-source evidence and grouped findings.",
        failures=["Claims 50 pages without visited URLs.", "No deduplication.", "Only one page is inspected."],
        tags=["browser", "internet", "long"],
        size="long-running",
        timeout=1200,
        assertions={
            "tools_all": ["browser.open:research_pages"],
            "urls_min": 10,
            "bot_reply_contains_any": ["sources", "results", "pages"],
        },
    ),
    case(
        16,
        "website_monitoring",
        "Check a website for new content.",
        "Go to this show's page and tell me if a new episode is out.",
        "Check this web page, compare the latest episode or release information against what was previously available, and tell me whether anything new has been published.",
        "Go to {{episode_url}} and tell me whether a new episode is out, including the evidence you used.",
        tools=["browser.control:check_page_update"],
        expected="The agent inspects the page, extracts release/episode markers, and reports current latest item.",
        pass_criteria="The answer includes current evidence from the page.",
        failures=["No page inspection.", "Answer has no evidence.", "Previous state is invented."],
        setup=["local_web_fixture"],
        tags=["browser", "safe"],
        assertions={
            "tools_all": ["browser.control:check_page_update"],
            "metadata_any": ["browser_url", "browser_state", "page_title"],
            "bot_reply_contains_any": ["episode", "released", "evidence", "new"],
        },
    ),
    case(
        17,
        "browser_form_fill",
        "Open and fill a browser form, stopping before submit.",
        "Open this page and start filling the form with this information.",
        "Go to this web form, fill the fields using the information I give you, stop before submitting, and show me a screenshot so I can review it.",
        "Go to {{form_url}} and fill the form with name=Oney, email=oney@example.com, message=Hello from E2E. Do not submit. Send me a screenshot so I can review it.",
        tools=["browser.open:open", "browser.control:extract_page_state", "browser.control:fill_form_step", "browser.open:screenshot", "artifact.deliver:send_screenshot"],
        expected="The agent opens the exact target tab, detects fields, fills values, does not submit, captures screenshot, and sends it.",
        pass_criteria="Filled-field evidence includes name/email/message, submitted=false, and Telegram receives a screenshot.",
        failures=["Wrong tab is filled.", "The form is submitted.", "Fields contain instruction text.", "No screenshot is delivered."],
        setup=["local_web_fixture"],
        tags=["browser", "form", "telegram_delivery"],
        assertions={
            "tools_all": ["browser.control:extract_page_state", "browser.control:fill_form_step", "browser.open:screenshot", "artifact.deliver:send_screenshot"],
            "metadata_any": ["browser_state", "screenshot_path"],
            "filled_fields_all": ["name", "email", "message"],
            "form_submitted": False,
            "telegram_media_min": 1,
        },
    ),
    case(
        18,
        "intent_based_tool_routing",
        "Route tools based on natural-language intent.",
        "Use Codex to create a simple app.",
        "Use GitHub Copilot in VS Code and web search to research this API, then implement a small adapter for it.",
        "Use GitHub Copilot in VS Code and web search to research a fake weather API, then implement a small adapter proposal for it.",
        tools=["LLM intent router", "browser.open:research_pages", "coding.agent:run_step or vscode.copilot_terminal", "adapter.factory:scaffold"],
        expected="The LLM router emits structured intent and the plan uses the explicitly requested tools.",
        pass_criteria="The route decision explains the selected tools and includes no brittle command-only matching evidence.",
        failures=["Regex-only route selected.", "Requested tool ignored.", "Plan is not validated against registry."],
        tags=["browser", "external_agent", "adapter_factory"],
        size="medium",
        timeout=900,
        assertions={
            "plan_required": True,
            "tools_any": ["browser.open:research_pages", "adapter.factory:scaffold", "vscode.copilot_terminal", "coding.agent:run_step"],
            "provider_any": ["github_copilot", "copilot"],
        },
    ),
    case(
        19,
        "no_external_agent_without_request",
        "Do not invoke Codex or Copilot unless explicitly requested.",
        "Create a small Python script.",
        "Build a simple app, but do not use Codex or GitHub Copilot unless I explicitly ask.",
        "Create a small modern web app about hamsters and mice and launch it, but do not use Codex or GitHub Copilot.",
        tools=["workspace.manage:web_app_preview"],
        expected="The agent uses local workspace capabilities and does not invoke Codex/Copilot.",
        pass_criteria="No external coding provider tool is invoked; preview URL/workspace evidence is produced.",
        failures=["Codex/Copilot is invoked despite no explicit request.", "No local output is created.", "The launched result has no preview URL."],
        tags=["workspace", "safe"],
        timeout=360,
        assertions={
            "tools_forbidden": ["coding.agent", "vscode.copilot_terminal"],
            "tools_any": ["workspace.manage:web_app_preview", "workspace.manage:launch_static"],
            "metadata_any": ["workspace_dir", "preview_url"],
            "urls_min": 1,
        },
    ),
    case(
        20,
        "codex_app_creation",
        "Use Codex when explicitly asked to build an app.",
        "Use Codex to create a basic todo app.",
        "Use Codex to create a mobile-oriented LLM deployment app with a simple UI, model selection, prompt input, response display, and deployment instructions.",
        "Use Codex to create a basic todo app in the task workspace, then report the files that changed.",
        tools=["coding.agent:plan", "coding.agent:run_goal"],
        expected="The orchestrator plans, prompts Codex, monitors output, inspects created files, and reports what Codex built.",
        pass_criteria="A workspace exists with generated files and Codex is the provider.",
        failures=["Local LLM writes the app directly.", "No workspace output.", "Codex output is not inspected."],
        tags=["external_agent", "codex", "long"],
        size="long-running",
        timeout=1200,
        assertions={
            "tools_any": ["coding.agent:run_goal", "coding.agent:run_step"],
            "provider": "codex",
            "metadata_any": ["coding_agent_workspace", "workspace_dir"],
        },
    ),
    case(
        21,
        "copilot_app_creation",
        "Use GitHub Copilot when explicitly asked to build code in VS Code.",
        "Use GitHub Copilot to create a simple React component.",
        "Use GitHub Copilot in VS Code to create a dashboard page, then inspect the generated code and tell me what was created.",
        "Use GitHub Copilot in VS Code to create a simple React component in the task workspace, then inspect the generated code and tell me what changed.",
        tools=["vscode.copilot_terminal or coding.agent:run_goal provider=github_copilot"],
        expected="The orchestrator routes through Copilot/VS Code, observes resulting files, and reports actual changes.",
        pass_criteria="Copilot is the provider and changed files are reported.",
        failures=["Local generator creates code instead of Copilot.", "Generated files are not inspected.", "Tool availability errors are hidden."],
        tags=["external_agent", "copilot", "long"],
        size="long-running",
        timeout=1200,
        assertions={
            "tools_any": ["vscode.copilot_terminal", "coding.agent:run_goal", "coding.agent:run_step"],
            "provider_any": ["github_copilot", "copilot"],
            "metadata_any": ["coding_agent_workspace", "workspace_dir"],
        },
    ),
    case(
        22,
        "vscode_file_tree_visibility",
        "Show/report the current coding workspace state.",
        "Tell me what files are in the project.",
        "Give me a screenshot of VS Code and the file directory, then summarize the current project structure.",
        "Give me a screenshot of VS Code and the file directory, then summarize the current project structure.",
        tools=["computer.use:observe", "filesystem.manage:inspect_folder", "artifact.deliver:send_screenshot"],
        expected="The agent inspects workspace files and captures VS Code/desktop state when requested.",
        pass_criteria="Screenshot and file tree summary match the actual workspace.",
        failures=["Screenshot is stale.", "File tree is guessed.", "No workspace state is consulted."],
        tags=["desktop", "filesystem", "telegram_delivery"],
        assertions={
            "tools_any": ["computer.use:observe", "filesystem.manage:inspect_folder"],
            "metadata_any": ["desktop_observation", "screenshot_path", "entries"],
            "bot_reply_contains_any": ["files", "VS Code", "workspace", "project"],
        },
    ),
    case(
        23,
        "presentation_external_tool",
        "Create/revise PowerPoint through Codex or a presentation adapter, not local LLM direct generation.",
        "Use the presentation-generation adapter to create a 5-slide PowerPoint from these notes.",
        "Use Codex or another appropriate presentation-generation adapter to create a PowerPoint presentation that looks like this style, exports the file, sends it to me, then accepts my next message as revision instructions.",
        "Use Codex to prepare the content for a 5-slide PowerPoint about local LLM deployment, then use the presentation-generation adapter to create the PPTX and send it to me.",
        tools=["coding.agent:run_goal", "document.manage:create_presentation", "artifact.deliver:send_file"],
        expected="The local LLM orchestrates. Codex or a presentation adapter creates content/assets; document adapter exports PPTX.",
        pass_criteria="The PPTX exists, is sent to Telegram, and the document step consumes external-tool output or explicit adapter content.",
        failures=["Local LLM directly writes the entire PPTX content with no external/tool step.", "No file is delivered.", "Follow-up context is lost."],
        tags=["external_agent", "codex", "presentation", "telegram_delivery", "long"],
        size="long-running",
        timeout=1200,
        assertions={
            "tools_all": ["coding.agent", "document.manage:create_presentation", "artifact.deliver:send_file"],
            "provider": "codex",
            "metadata_any": ["document_path"],
            "telegram_media_min": 1,
        },
    ),
    case(
        24,
        "general_adapter_creation",
        "Create/configure a reusable adapter for a missing capability.",
        "Create an adapter for the Yahoo Finance stock data API that can fetch the latest price, daily change, and basic quote information for a given ticker symbol.",
        "I need an adapter that lets the orchestrator interact with VS Code, send prompts to Codex, read Codex output, detect file changes, and report progress.",
        "Create an adapter for the Yahoo Finance stock data API that can fetch the latest price, daily change, and basic quote information for a given ticker symbol. Put it in the adapter cache and do not load it automatically.",
        tools=["adapter.factory:scaffold", "code review/checker"],
        expected="The system designs a reusable adapter proposal, isolates it in cache, and records review/activation status.",
        pass_criteria="Adapter proposal files exist and are generic, not hard-coded for one ticker.",
        failures=["Adapter is hardcoded to one prompt.", "Proposal is auto-loaded without review.", "No tests or manifest are created."],
        tags=["adapter_factory", "safe"],
        assertions={
            "tools_all": ["adapter.factory:scaffold"],
            "metadata_any": ["adapter_dir", "adapter_name"],
            "local_paths_min": 1,
        },
    ),
    case(
        25,
        "codex_vscode_adapter",
        "Use a Codex adapter inside VS Code.",
        "Use the Codex VS Code adapter to ask Codex to create a new component.",
        "Use the Codex VS Code adapter to open the project, prompt Codex to implement authentication, watch the output, detect completion, inspect changed files, and report the result.",
        "Use the Codex VS Code adapter to create a new component in the current project, watch for completion, inspect changed files, and report the result.",
        tools=["codex.vscode or coding.agent:run_step provider=codex", "computer.use:observe"],
        expected="The adapter launches/focuses VS Code, sends Codex a bounded prompt, watches output/files, and reports status.",
        pass_criteria="The adapter can be reused and reports actual changed files or a clear availability error.",
        failures=["No VS Code/Codex interaction.", "Completion is assumed blindly.", "Changed files are not inspected."],
        tags=["external_agent", "codex", "vscode", "long"],
        size="long-running",
        timeout=1200,
        assertions={
            "tools_any": ["coding.agent:run_step", "coding.agent:run_goal", "codex.vscode"],
            "provider": "codex",
            "metadata_any": ["coding_agent_workspace", "changed_files", "coding_agent_session_id"],
        },
    ),
    case(
        26,
        "copilot_vscode_adapter",
        "Use a GitHub Copilot adapter inside VS Code.",
        "Use the Copilot adapter to generate a helper function.",
        "Use the Copilot adapter in VS Code to implement a dashboard, review the generated code, fix issues, and report what changed.",
        "Use the Copilot adapter in VS Code to generate a helper function, inspect the file changes, and report what changed.",
        tools=["vscode.copilot_terminal or coding.agent:run_step provider=github_copilot"],
        expected="The adapter routes through Copilot, observes generated code, detects errors/limits, and reports actual changes.",
        pass_criteria="Copilot is invoked and changed files or a clear availability error are reported.",
        failures=["Local generator is used instead.", "Copilot result is not observed.", "Limit/unavailable message is misclassified."],
        tags=["external_agent", "copilot", "vscode", "long"],
        size="long-running",
        timeout=1200,
        assertions={
            "tools_any": ["vscode.copilot_terminal", "coding.agent:run_step", "coding.agent:run_goal"],
            "provider_any": ["github_copilot", "copilot"],
            "metadata_any": ["changed_files", "coding_agent_workspace"],
        },
    ),
    case(
        27,
        "browser_chatgpt_adapter",
        "Interact with a browser web app such as ChatGPT.",
        "Open ChatGPT in the browser, type this prompt, and read the answer.",
        "Launch the browser, open ChatGPT, enter a prompt, wait for the response, read the response, and use it as input to the next step of a larger workflow.",
        "Open ChatGPT in the browser, type a short prompt asking for a one-line greeting, wait for the response, and report what it answered.",
        tools=["browser.open:open", "browser.control:fill_form_step/click", "browser.control:extract_page_state"],
        expected="Browser interaction is treated as an adapter capability: open, type, wait, read, screenshot, continue.",
        pass_criteria="The response is read from the browser state and can be used in a later step.",
        failures=["The agent fabricates a ChatGPT answer.", "Login/session blocker is not reported.", "No browser state is captured."],
        tags=["browser", "external_web_app", "long"],
        size="long-running",
        timeout=900,
        assertions={
            "tools_any": ["browser.open:open", "browser.control:fill_form_step", "browser.control:extract_page_state"],
            "metadata_any": ["browser_state", "browser_url", "page_title"],
        },
    ),
    case(
        28,
        "planning_progress_cadence",
        "Create a plan for complex tasks and honor progress cadence.",
        "Make a plan to build a simple web app, tell me the plan, then start executing it.",
        "Use Codex to build a large web application with authentication, dashboard, database, scheduled jobs, user settings, and admin tools. First create a plan, tell me the plan, then start implementing one stage at a time. Give me a progress update every five minutes.",
        "Build a simple web app with login and a dashboard. Give me a progress update every one minute.",
        tools=["LLM planner", "workspace.manage or coding.agent", "progress notifier"],
        expected="The orchestrator creates an internal plan for complex work, shows it if requested, starts execution, and schedules real progress updates.",
        pass_criteria="A persisted plan exists, execution begins, and progress cadence is honored when task duration requires it.",
        failures=["Only a plan is returned with no execution.", "No persisted plan.", "Progress updates are generic or fake."],
        tags=["planning", "long"],
        size="long-running",
        timeout=900,
        assertions={
            "plan_required": True,
            "tools_any": ["workspace.manage", "coding.agent:run_step", "coding.agent:run_goal"],
            "progress_updates_min": 1,
        },
    ),
    case(
        29,
        "iterative_codex_execution",
        "Use Codex one meaningful step at a time.",
        "Use Codex to create the project structure, then stop and report.",
        "Use Codex to build this app. Send Codex one implementation step, wait for the result, inspect what changed, report progress, then send the next step.",
        "Use Codex to create the project structure for a small app, then stop and report what changed.",
        tools=["coding.agent:plan", "coding.agent:run_step"],
        expected="The orchestrator sends Codex bounded steps, waits for completion, inspects files, and decides next action.",
        pass_criteria="Each Codex step has purpose, output inspection, and follow-up decision.",
        failures=["Entire project dumped into one prompt.", "Next step starts before previous completion.", "No result inspection."],
        tags=["external_agent", "codex", "long"],
        size="long-running",
        timeout=1200,
        assertions={
            "tools_all": ["coding.agent:run_step"],
            "provider": "codex",
            "metadata_any": ["changed_files", "coding_agent_workspace", "current_step_index"],
        },
    ),
    case(
        30,
        "codex_progress_monitoring",
        "Monitor Codex activity and report current status.",
        "What is Codex doing right now?",
        "While Codex is building the app, monitor VS Code, terminal output, file changes, and Codex messages. Send me progress updates through chat or Telegram.",
        "What is Codex doing right now? Check actual Codex/tool/workspace state before answering.",
        tools=["coding.agent:status", "filesystem.manage:inspect_folder", "computer.use:observe"],
        expected="The answer is grounded in actual Codex session state, file changes, terminal output, or desktop observation.",
        pass_criteria="Status includes current step, completed work, blocked state, or no-active-session evidence.",
        failures=["Generic estimated status.", "No tool state consulted.", "Reports Codex running when it is not."],
        tags=["external_agent", "codex"],
        timeout=360,
        assertions={
            "tools_any": ["coding.agent:status", "computer.use:observe", "filesystem.manage:inspect_folder"],
            "metadata_any": ["coding_agent_status", "coding_agent_session_id", "desktop_observation"],
            "bot_reply_contains_any": ["Codex", "status", "running", "no active", "blocked"],
        },
    ),
    case(
        31,
        "status_during_long_work",
        "Answer user status questions during long-running work.",
        "Where are we?",
        "Tell me what has been completed, what Codex is doing now, what is left in the plan, and whether anything is blocked.",
        "Where are we? Tell me what has been completed, what is happening now, what remains, and whether anything is blocked.",
        tools=["task repository", "plan repository", "coding.agent:status"],
        expected="The agent consults current plan, task state, workspace, and tool state before answering.",
        pass_criteria="The status is specific, current, and grounded in actual progress.",
        failures=["Status is generic.", "Plan state is ignored.", "Blocked/error state is omitted."],
        tags=["status"],
        assertions={
            "tools_any": ["coding.agent:status", "task.status", "filesystem.manage:inspect_folder"],
            "metadata_any": ["plan", "task_status", "coding_agent_status"],
            "bot_reply_contains_any": ["completed", "current", "left", "blocked", "status"],
        },
    ),
    case(
        32,
        "codex_completion_detection",
        "Detect when Codex finishes a step.",
        "Tell me when Codex finishes this step.",
        "After Codex completes each implementation step, inspect the output, summarize what changed, and decide whether the next planned step can begin.",
        "Use Codex to make one tiny file change, wait until it finishes, inspect the output, and tell me what changed.",
        tools=["coding.agent:run_step", "coding.agent:status", "filesystem watcher"],
        expected="The orchestrator detects completion through status, output, file changes, or terminal state before continuing.",
        pass_criteria="The report includes completion evidence and changed files or no-change explanation.",
        failures=["Continues before tool is done.", "Assumes completion without evidence.", "No output inspection."],
        tags=["external_agent", "codex", "long"],
        size="long-running",
        timeout=1200,
        assertions={
            "tools_all": ["coding.agent:run_step"],
            "provider": "codex",
            "metadata_any": ["changed_files", "completion_state", "coding_agent_session_id"],
        },
    ),
    case(
        33,
        "error_detection_recovery",
        "Detect build/test errors and attempt recovery.",
        "Run the app and fix errors.",
        "After Codex creates the app, run tests or build commands, inspect errors, ask Codex or Copilot to fix them, and repeat until the app builds or a real blocker is found.",
        "Run the current app, inspect any errors, attempt one fix if possible, and report what failed and what you tried.",
        tools=["terminal.run", "coding.agent:run_step", "workspace inspection"],
        expected="The agent uses logs/tests/build output to guide repair and reports attempts and blockers.",
        pass_criteria="Errors are captured, a concrete fix attempt occurs when possible, and the final state is reported.",
        failures=["Errors ignored.", "Fix attempt is unguided.", "Failure details are hidden."],
        tags=["external_agent", "codex", "long"],
        size="long-running",
        timeout=1200,
        assertions={
            "tools_any": ["terminal.run", "coding.agent:run_step", "workspace.manage"],
            "metadata_any": ["errors", "terminal_output", "repair_attempts"],
            "bot_reply_contains_any": ["error", "fixed", "failed", "blocked", "tried"],
        },
    ),
    case(
        34,
        "codex_limit_detection",
        "Detect Codex usage limits.",
        "Tell me if Codex is available.",
        "While Codex is working, detect if VS Code shows a message saying Codex messages are exhausted or unavailable, then tell me that the Codex limit has been reached.",
        "Tell me if Codex is available and whether a limit or quota message is currently visible.",
        tools=["coding.agent:limits", "computer.use:observe"],
        expected="The agent recognizes Codex availability, quota, exhausted, renewal, or unknown states.",
        pass_criteria="Limit condition is accurately reported and not confused with code errors.",
        failures=["Keeps retrying blindly after limit.", "Reports available without checking.", "Confuses code error with quota."],
        tags=["external_agent", "codex", "limits", "fault_injection_needed"],
        timeout=600,
        assertions={
            "final_status_in": ["completed", "blocked", "failed"],
            "tools_any": ["coding.agent:limits", "coding.agent:status", "computer.use:observe"],
            "metadata_any": ["coding_agent_limit_state"],
            "bot_reply_contains_any": ["Codex", "limit", "available", "quota", "unknown"],
        },
    ),
    case(
        35,
        "copilot_limit_detection",
        "Detect GitHub Copilot limits or unavailable state.",
        "Tell me if GitHub Copilot is available.",
        "Use Copilot for this coding task. If Copilot shows a limit, subscription, quota, or unavailable message, detect it and report it.",
        "Tell me if GitHub Copilot is available and report any quota, subscription, or unavailable message.",
        tools=["vscode.copilot_terminal or coding.agent:limits provider=github_copilot", "computer.use:observe"],
        expected="The agent distinguishes Copilot availability problems from coding errors.",
        pass_criteria="Availability/limit state is accurately reported or marked unknown with evidence.",
        failures=["Retries blindly after quota.", "Availability is guessed.", "Limit and code error are conflated."],
        tags=["external_agent", "copilot", "limits", "fault_injection_needed"],
        timeout=600,
        assertions={
            "final_status_in": ["completed", "blocked", "failed"],
            "tools_any": ["coding.agent:limits", "vscode.copilot_terminal", "computer.use:observe"],
            "metadata_any": ["coding_agent_limit_state", "copilot_limit_state"],
            "bot_reply_contains_any": ["Copilot", "limit", "available", "quota", "unknown"],
        },
    ),
    case(
        36,
        "codex_limit_resume",
        "Resume automatically after Codex limit reset.",
        "If Codex is unavailable, continue when it comes back.",
        "Use Codex to build this app. If Codex reaches its usage limit and says it renews at 10:00 AM, save the plan, save current progress, schedule a continuation for 10:00 AM, and resume the same task from where it stopped.",
        "Use Codex for a task that should pause on usage limit, save the plan, schedule continuation after reset, and resume from the saved step.",
        tools=["coding.agent:run_step", "schedule.manage:create", "coding.agent:resume"],
        expected="The agent stores plan/workspace state, parses reset time, schedules continuation, and resumes from current step.",
        pass_criteria="Continuation preserves the plan and workspace instead of restarting.",
        failures=["Plan is lost.", "Resume starts from scratch.", "Reset time is ignored."],
        tags=["external_agent", "codex", "limits", "fault_injection_needed", "long"],
        size="long-running",
        timeout=1200,
        assertions={
            "final_status_in": ["completed", "blocked", "retrying"],
            "tools_any": ["schedule.manage:create", "coding.agent:resume", "coding.agent:run_step"],
            "metadata_any": ["next_retry_at", "coding_agent_limit_state", "coding_agent_session_id"],
        },
    ),
    case(
        37,
        "copilot_limit_resume",
        "Resume automatically after Copilot limit reset.",
        "If Copilot is unavailable, resume when it is available again.",
        "Use GitHub Copilot to implement this feature. If Copilot reaches a limit or becomes temporarily unavailable, detect when it can be used again, schedule a continuation, and resume from the saved plan.",
        "Use GitHub Copilot for a task that should pause on limit, save the plan, schedule continuation, and resume from the saved step.",
        tools=["vscode.copilot_terminal", "schedule.manage:create", "coding.agent:resume"],
        expected="Copilot interruptions are persisted and resumed the same way as Codex interruptions.",
        pass_criteria="Resume preserves plan, context, and workspace.",
        failures=["Copilot limit causes repeated retries.", "No continuation is scheduled.", "Workspace context is lost."],
        tags=["external_agent", "copilot", "limits", "fault_injection_needed", "long"],
        size="long-running",
        timeout=1200,
        assertions={
            "final_status_in": ["completed", "blocked", "retrying"],
            "tools_any": ["schedule.manage:create", "coding.agent:resume", "vscode.copilot_terminal"],
            "metadata_any": ["next_retry_at", "copilot_limit_state", "coding_agent_session_id"],
        },
    ),
    case(
        38,
        "scheduled_jobs",
        "Create recurring scheduled jobs.",
        "Create a job that runs every day and checks this website.",
        "Set up a scheduled job that runs every morning, searches the internet for this topic, summarizes new results, and sends me the summary.",
        "Create a job that runs every day and checks {{episode_url}} for a new episode, then sends me the summary.",
        tools=["schedule.manage:create"],
        expected="The agent creates a schedule with cadence, objective, and output behavior.",
        pass_criteria="A schedule record exists with next run time and task definition.",
        failures=["No schedule created.", "Schedule has no output channel.", "Objective is not preserved."],
        setup=["local_web_fixture"],
        tags=["schedule", "browser"],
        assertions={
            "tools_all": ["schedule.manage:create"],
            "metadata_any": ["schedule_id", "schedule_next_run_at"],
            "schedule_created": True,
        },
    ),
    case(
        39,
        "scheduled_development_continuation",
        "Schedule continuation for paused development work.",
        "Schedule this coding task to continue tomorrow.",
        "Codex is out of messages until 10:00 AM. Schedule a job that reopens the workspace at 10:00 AM, checks Codex availability, reloads the saved plan, and continues the next implementation step.",
        "Codex is out of messages until tomorrow at 10:00 AM. Schedule a job to reopen the workspace, check Codex availability, reload the saved plan, and continue the next implementation step.",
        tools=["schedule.manage:create", "coding.agent:resume"],
        expected="The scheduled job is tied to paused development state and resumes the same plan.",
        pass_criteria="Continuation task references existing plan/workspace and reports after resuming.",
        failures=["Creates only a reminder.", "No plan/workspace reference.", "Restarts from the beginning."],
        tags=["external_agent", "codex", "schedule", "long"],
        size="long-running",
        timeout=900,
        assertions={
            "tools_all": ["schedule.manage:create"],
            "metadata_any": ["schedule_id", "coding_agent_session_id", "plan_artifact_id"],
            "schedule_created": True,
        },
    ),
    case(
        40,
        "large_web_app_orchestration",
        "Manage a large web app workflow end to end.",
        "Use Codex to build a simple app with login and a dashboard.",
        "Use Codex to build a large web application with authentication, dashboard pages, database models, scheduled jobs, settings, admin tools, tests, and deployment instructions. Create a plan, implement one stage at a time, monitor Codex, send progress updates, detect limits, schedule continuation if needed, and continue until the app is complete or blocked.",
        "Use Codex to build a simple app with login and a dashboard. Create a plan, implement one stage, inspect the result, and report progress.",
        tools=["coding.agent:plan", "coding.agent:run_step", "terminal.run", "artifact.deliver"],
        expected="The orchestrator acts as project manager and tool operator, not just a prompt forwarder.",
        pass_criteria="A meaningful implementation stage completes or a real blocker is reported with plan continuity.",
        failures=["No plan.", "No result inspection.", "Progress is fake.", "Limit handling is absent."],
        tags=["external_agent", "codex", "long"],
        size="long-running",
        timeout=1800,
        assertions={
            "plan_required": True,
            "tools_any": ["coding.agent:run_step", "coding.agent:run_goal"],
            "provider": "codex",
            "metadata_any": ["coding_agent_workspace", "changed_files", "current_step_index"],
            "progress_updates_min": 1,
        },
    ),
    case(
        41,
        "natural_language_orchestration",
        "Understand natural language and route intelligently.",
        "Use the coding assistant for this part and then check the browser result.",
        "Build this feature using the best available coding adapter, check documentation online, update the app, run it, screenshot the result, and tell me what changed.",
        "Search the web for Python official documentation, create a short note in {{documents_folder}}, and send me the result.",
        tools=["LLM intent router", "browser.open:research", "filesystem.manage or workspace.manage", "artifact.deliver"],
        expected="The orchestrator infers adapters from intent/context and validates the plan against the registry.",
        pass_criteria="The selected tools match the requested workflow and the final outputs are delivered.",
        failures=["Only exact phrase matching works.", "Tools are selected without registry validation.", "Multi-step workflow stalls."],
        setup=["documents_fixture"],
        tags=["browser", "filesystem", "telegram_delivery"],
        timeout=600,
        assertions={
            "plan_required": True,
            "tools_any": ["browser.open:research", "workspace.manage", "filesystem.manage", "artifact.deliver"],
            "metadata_any": ["route_decision", "validated_plan", "document_path", "last_artifact_ids"],
        },
    ),
    case(
        42,
        "multi_tool_workflow",
        "Combine browser, desktop, files, coding tools, and output delivery.",
        "Search the web, create a file from the results, and show me the folder.",
        "Research a topic online, create a small app from the research, use Codex to implement it, use VS Code to inspect it, run the app, take a screenshot, create a short PowerPoint summary through an appropriate external tool or adapter, and send me the outputs.",
        "Research local LLM deployment online, create a short note file from the result, show me the output folder, and send me the file.",
        tools=["browser.open:research", "workspace.manage", "computer.use:observe", "artifact.deliver"],
        expected="The orchestrator coordinates tools as one workflow and delivers final artifacts.",
        pass_criteria="Each tool is used for the right purpose and delivered artifacts correspond to the task.",
        failures=["Workflow loses context between tools.", "File is not created.", "Output delivery sends wrong artifact."],
        tags=["browser", "filesystem", "telegram_delivery", "long"],
        size="long-running",
        timeout=900,
        assertions={
            "tools_any": ["browser.open:research", "workspace.manage", "filesystem.manage", "artifact.deliver"],
            "metadata_any": ["document_path", "workspace_dir", "last_artifact_ids"],
            "telegram_media_min": 1,
        },
    ),
    case(
        43,
        "output_delivery",
        "Send outputs created by a task.",
        "Send me the file you created.",
        "After completing the task, send me the generated PowerPoint, code files, screenshots, summary report, and any logs needed to understand what happened.",
        "Create a small text output in {{documents_folder}} named e2e-output.txt, then send me that file.",
        tools=["workspace.manage or document.manage", "artifact.deliver:send_file"],
        expected="The agent collects task outputs and sends the exact generated file(s), without falling back to stale cached artifacts.",
        pass_criteria="Delivered files are complete, correctly named, and tied to this task.",
        failures=["Recent artifact cache is used.", "Wrong file sent.", "Output is only described, not delivered."],
        setup=["documents_fixture"],
        tags=["telegram_delivery"],
        assertions={
            "tools_all": ["artifact.deliver:send_file"],
            "telegram_media_min": 1,
            "metadata_any": ["document_path", "artifact_ids", "last_artifact_ids"],
        },
    ),
    case(
        44,
        "followup_revision",
        "Revise a previous output using preserved context.",
        "Change the title and send it again.",
        "Revise the PowerPoint based on this feedback, update the design, keep the previous structure, regenerate the file, and send the new version.",
        "Revise the previous PowerPoint title to Local LLM Deployment Update, keep the previous structure, regenerate it, and send the revised output.",
        tools=["memory/context", "document.manage:update_presentation", "artifact.deliver:send_file"],
        expected="The agent uses prior task context to modify the previous output instead of starting unrelated work.",
        pass_criteria="The revised artifact reflects requested changes and preserves relevant prior structure.",
        failures=["Previous artifact is not found.", "Revision starts from scratch.", "No revised file is sent."],
        tags=["followup", "presentation", "telegram_delivery", "long"],
        size="long-running",
        timeout=900,
        depends_on=["presentation_external_tool"],
        assertions={
            "tools_all": ["document.manage:update_presentation", "artifact.deliver:send_file"],
            "metadata_any": ["document_path", "previous_artifact_id", "revision_artifact_id"],
            "telegram_media_min": 1,
        },
    ),
    case(
        45,
        "audit_trail_final_summary",
        "Summarize actions, changed files, errors, skipped items, and next steps.",
        "Tell me what you changed.",
        "After organizing files or building the app, give me a clear summary of actions taken, files changed, folders created, errors encountered, skipped items, and next recommended steps.",
        "Organize {{documents_folder}} by file names, then give me a clear summary of actions taken, files changed, folders created, errors encountered, skipped items, and next steps.",
        tools=["filesystem.manage:organize_plan", "filesystem.manage:apply_manifest", "audit trail"],
        expected="The final message summarizes actual tool actions and audit evidence.",
        pass_criteria="The summary matches changed paths, folders, errors, skipped items, and final status in trace logs.",
        failures=["Summary claims changes not in audit logs.", "Errors are hidden.", "No next-step/blocker detail."],
        setup=["documents_fixture"],
        tags=["filesystem", "audit"],
        assertions={
            "tools_all": ["filesystem.manage:organize_plan", "filesystem.manage:apply_manifest"],
            "metadata_any": ["changed_paths", "manifest", "audit_summary"],
            "changed_paths_min": 1,
            "bot_reply_contains_any": ["changed", "folders", "errors", "skipped", "next"],
        },
    ),
    case(
        46,
        "voice_message_intake",
        "Transcribe a Telegram voice message and route it like text.",
        "Send a voice message saying: tell me what is on my desktop right now.",
        "Send a Telegram voice message containing a desktop inspection request; the agent should transcribe it, spawn the same task it would for text, and keep the transcript in the audit trail.",
        "Tell me what is on my desktop right now.",
        tools=["telegram voice intake", "stt.transcribe", "computer.use:observe"],
        expected="The Telegram intake downloads the voice file, transcribes it, stores transcript evidence, classifies the transcript, and spawns the correct task.",
        pass_criteria="A task is spawned from the transcript, voice metadata is present, and the planned tool matches the transcribed request.",
        failures=["Voice enters classifier with empty text.", "STT failure is hidden.", "Transcript is not logged.", "The voice task is routed differently from the same text request."],
        tags=["voice", "stt", "desktop"],
        size="medium",
        timeout=420,
        input_kind="voice",
        assertions={
            "tools_all": ["computer.use:observe"],
            "metadata_any": ["voice_transcript", "voice_file_id", "desktop_observation", "screenshot_path"],
            "bot_reply_contains_any": ["task_", "desktop", "screenshot"],
        },
    ),
]


def main() -> None:
    numbers = [item["number"] for item in CASES]
    expected = [1, 2, 3, 4, 5, 6, 7, 8, *range(10, 47)]
    if numbers != expected:
        raise SystemExit(f"case numbers must match {expected}, got {numbers}")
    ids = [item["id"] for item in CASES]
    if len(ids) != len(set(ids)):
        raise SystemExit("case ids must be unique")
    CASES_PATH.write_text(json.dumps(CASES, indent=2) + "\n", encoding="utf-8")
    print(f"Wrote {len(CASES)} live E2E cases to {CASES_PATH}")


if __name__ == "__main__":
    main()
